### ISSUE TITLE
Can you tell us how long do you train for each datasets?

### ISSUE THREAD

**Issue by wode-czw** [thunguyenphuoc/HoloGAN#1]
I want to know how much time do you spent and how much GPU do you used in the same time?
the paper doesn't show me this infomation.thanks!

**Comment by thunguyenphuoc** [comment]
Hello. 
I trained HoloGAN with 1 GPU (GTX 1080 Ti), 50 epochs for each model/dataset.

**Comment by xiaobaozi1996** [comment]
Hello, will it spend a long time such as 3~4 days for one dataset?
