### ISSUE TITLE
Where can download the  supplemental document?

### ISSUE THREAD

**Issue by xiaobaozi1996** [thunguyenphuoc/HoloGAN#5]
![image](https://user-images.githubusercontent.com/31682925/68373570-2666cd80-017e-11ea-8e5d-2fa7ce0a05cc.png)
The paper has mentioned this paper will provid a supplemental document. I haven't found it yet. Could you give me a downloading link?

**Comment by NTU-P04922004** [comment]
You can find it here:

[ICCV 2019 open access](http://openaccess.thecvf.com/content_ICCV_2019/html/Nguyen-Phuoc_HoloGAN_Unsupervised_Learning_of_3D_Representations_From_Natural_Images_ICCV_2019_paper.html)

**Comment by xiaobaozi1996** [comment]
Thanks，get it！
